#!/bin/sh

presets=${TM_LAYOUTS_DIR:-"${XDG_DATA_HOME:-$HOME/.local/share}/tmux-companion"}
target="$presets/$1.presets"
basename=$(basename "$target" | tr '[:lower:]' '[:upper:]' | cut -d. -f1)
editor=${EDITOR:-vi}

die() { printf '%s: %s.\n' "$0" "$1" >&2; exit 1; }

gen_target() {
cat <<EOF >"$target"
#!/bin/sh
# Welcome to the default preset for tmux-companion. As you can see this is a
# POSIX shellscript but you can use whatever POSIX compatible shell language
# you'd like.

###############################################################################
# BE CAREFULL THIS CAN DESTROY YOUR SYSTEM IF YOU DON'T KNOW WHAT YOU ARE DOING
###############################################################################

# This is here to prevent re-executon when switching between sessions
if [ -z "\$TM_LOCK_$basename" ] && [ -n "\$TMUX" ]; then
    export TM_LOCK_$basename=1
fi

# You can run whatever tmux command you want:
# tmux new-window -d top
# tmux spilt-window python3
# tmux spilt-window ipython
EOF
}

main() {
    if [ -d "$presets" ]; then
        ! [ -f "$target" ] \
            && gen_target
        $editor "$target"
    else
        die "$presets directory doesn't exitst"
    fi
}

main "$@"
